### ISSUE TITLE
CSS Minify breaks calc function

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#287] opened 2020-10-09 11:51 UTC
When CSS minify is enabled CSS minifier: Minify(default) it removes space in calc() function:
```
.form-select-hint::before{
  left:calc(50%  +  1.5em);
}
.form-select-hint::after{
  right:calc(50% + 1.5em);
}
```
After CSS minify:
`.form-select-hint::before{left:calc(50%+1.5em)}.form-select-hint::after{right:calc(50% + 1.5em)}`
If CSS minifier is switched to CSS tidy the issue does not persist.
Reference topic: https://wordpress.org/support/topic/minify-css-and-calc-function-broken/

**Comment by ericek111** [comment] 2020-10-13 13:01
We've experienced the same issue. This is my minimal test case:
```css
img {
    height: calc(1px + 1px);
}
a {
}
```
Before the bug does its job, this gets reduced to:
```css
img{min-height:calc(1px + 20px)}a{}
```

The ["remove ws in selectors" regex](https://github.com/W3EDGE/w3-total-cache/blob/master/lib/Minify/Minify/CSS/Compressor.php#L118) is too greedy and matches the whole CSS ruleset up to the next opening curly bracket.

Adding a lazy modifier to the first part of the regex corrects the behaviour. But my regex game is not that strong, so there may be (?) breakage.

```pecl
/
	(?:              # non-capture
		\\s*
		[^~>+,\\s]+  # selector part
		\\s*
		[,>+~]       # combinators
	)*?                  # changed this from `)+` to `)*?`
	\\s*
	[^~>+,\\s]+      # selector part
	{                # open declaration block
/x
```
This breaks horribly when there's a space between the selector and the curly bracket. But one of the previous regexes takes care of that, so it should be fine.

**Comment by maxicus** [comment] 2020-10-13 13:18
@ericek111 thanks for the hint.

Just FYI, that issue is well reproducible and now at the top priority, so will provide a fix to it in a near time.

**Comment by Lazerbeak12345** [comment] 2020-11-06 22:06
Here's another test case that breaks:

```
img {
    --a:1px;
    height: calc(var(--a) + var(--a));
}
```

This is particurally annoying because it reduces to this:

```
img {--a:1px;height:calc(var(--a)+var(--a))}
```

According to MDN, `+` and `-` both require whitespace around them.

**Comment by maxicus** [comment] 2020-11-11 15:16
@Lazerbeak12345 please check master. It should be fixed as you can see the fix was merged above.

**Closed** 2020-12-16 19:07 UTC
Labels: C: Minify, S: wp.org, bug
