### ISSUE TITLE
Store transients in database broken

### ISSUE THREAD

**Issue by maciejmackowiak** [W3EDGE/w3-total-cache#303] opened 2020-11-12 12:11 UTC
We are using w3 total cache 0.15.2 (same issue happens with 0.15.1)

And it looks like the setting to store transients in the databse is broken.

We have enabled object cache using memcached and enabled "Store transients in database" setting,
but the transients are not present in the DB and they are getting cleared when purging memcached.

Any idea why it is not working or how to debug what is broken?

**Comment by mavas84** [comment] 2020-11-12 17:04
Hello @maciejmackowiak 

Thank you for taking the time to open this issue.
We've made some tests for this. We used wp `transient delete-all` to clear all transients from the database.  I  activated Total Upkeep (since that creates transients), and transients were created in the database. 
You can try this:
```
$ wp transient delete-all
Success: 5 transients deleted from the database.

Warning: Transients are stored in an external object cache, and this command only deletes those stored in the database. You must flush the cache to delete all transients.
$ wp transient set test testing

Success: Transient added.
$ wp transient get test
testing
```
... and then check the wp_options table for the transient.
`SELECT `option_value` FROM `wp_options` WHERE `option_name` = '_transient_test';`

Thanks!

**Comment by maciejmackowiak** [comment] 2020-11-12 18:57
@mavas84 thanks for quick replay.

I've retested it on plain wp install with some default theme and only w3tc plugin and it looks like the culprit is Fragment Cache extension in w3tc pro mode. When the extension is activated and I use `set_transient('test','test');` it is not getting written to the DB but when I've deactivated the extension it is going to the DB.

Seems that this is related:
https://github.com/W3EDGE/w3-total-cache/blob/master/Extension_FragmentCache_Plugin.php#L60

**Comment by archon810** [comment] 2020-12-17 20:06
Any updates on the progress of the issue please?

**Comment by cssjoe** [comment] 2020-12-17 22:00
@archon810  Thank you for asking.  This issue will be addressed soon.  It is working it's way up the backlog.  The bug in this issue is that transients that are stored when using the fragment cache extension are not saved in the database.  They are stored in the engine chosen, and have a lifetime/expiration set in the plugin settings (wp-admin/admin.php?page=w3tc_fragmentcache), with a default of 180 seconds.

I see the issue https://github.com/Yoast/wordpress-seo/issues/15341 where you mentioned the issue here.  If someone does choose to cache transients, then the expiration time set may be shorter than a plugin specifies in the code.  Transients are meant to be temporary and could be cleared by WP-CLI commands and other plugins.  If a shorter transient lifetime causes issues, then the cache lifetime can be increased in the settings or transients can be excluded from the cache.

**Comment by cssjoe** [comment] 2020-12-23 18:04
It has been the expected behavior that when using the Fragment Cache Extension (pro feature), it changes the storage completely over to the engine of your choice and uses the default expiration set in the settings.  If you need a longer lifetime, then you can change it in the settings.  Since this is the excepted behavior and is a pro feature, I'll close this issue in this free plugin forum.  If any help is needed for pro features, then you can contact pro support.  For anything else, please feel free to let us know in this forum.  Thank you.

**Closed by cssjoe** 2020-12-23 18:04 UTC
Labels: S: GH, bug
