### ISSUE TITLE
[Bug] Manual Minify files are not being combined

### ISSUE THREAD

**Issue by joe9663** [W3EDGE/w3-total-cache#297] opened 2020-11-02 21:40 UTC
Files added using manual minification are not being combined when served to the browser. Individual files appear briefly but then they disappear.

Replicate by adding js / css files using minify:manual and the help wizard; neither js or css files are being combined or minified.

**Comment by cssjoe** [comment] 2020-11-02 22:25
There was a duplicate theme name, but a different slug/directory name.  The Minify options page JavaScript was being confused and hid the files listed.  When the inactive theme was moved out of the themes directory, the options page worked as expected.  The files started being minified.

**Comment by cssjoe** [comment] 2020-11-03 18:25
Closing this as it was caused by another issue.  I created https://github.com/W3EDGE/w3-total-cache/issues/298 for the issue that caused this behavior.

**Closed by cssjoe** 2020-11-03 18:25 UTC
